In [2]:
import numpy as np

Users of Python are drawn to ease of use, particularly dynamic typing. A statically-typed language like C or Java requires each variable to be explicitly declared, a dynamically-typed language like Python skips this specification. For example:

In [3]:
/* C code */
int result = 0;
for (int i = 0; i < 100; i++) {
    result += i;
}

SyntaxError: invalid syntax (<ipython-input-3-0a6eecce49b8>, line 1)

In Python, we can write the following:

In [7]:
# Python code
result = 0
for i in range(100):
    result += i

# A Python Integer is more than just an Integer

Keep in mind that the standard Python implementations are written in C. This means that every Python object is simply a cleverly disguised C structure. Check this out:

In [8]:
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};

SyntaxError: invalid syntax (<ipython-input-8-0f40127117db>, line 1)

Here is the **difference**: A C integer is essentially a label for a position in memory whose bytes encode an integer value. A Python integer is a pointer to a position in memory containing all the Python object information, including the bytes that contain the integer value. This extra information in the Python integer structure is what allows Python to be coded so freely and dynamically. All this additional information in Python types comes at a cost, however, which becomes especially apparent in structures that combine many of these objects.

# Using Numpy

While the built-in `array` module can be used to create dense arrays, we can actually just use the much more useful `ndarray` object of the NumPy package. While Python's `array` object provides efficient storage of array-based data, NumPy adds to this efficient operations on that data. We will explore these operations in later sections; here we'll demonstrate several ways of creating a NumPy array.

In [1]:
import numpy as np

In [2]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [3]:
np.array([1,2,3,4], dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [4]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
np.zeros(10, dtype=float)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [6]:
np.ones((3,5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [7]:
np.full((3, 5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [8]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [10]:
np.random.random((3,3))

array([[ 0.13081926,  0.02304279,  0.48656353],
       [ 0.04430761,  0.96099927,  0.95373651],
       [ 0.11576526,  0.03620092,  0.44679602]])

In [11]:
np.random.normal(0, 1, (3,3))

array([[-1.22104373,  1.86200277,  0.47152294],
       [-0.01820465, -1.5970422 ,  0.79359603],
       [ 0.11535186,  0.61008301,  2.00085301]])

In [12]:
np.random.randint(0, 10, (3,3))

array([[5, 6, 1],
       [5, 7, 6],
       [3, 1, 7]])

In [13]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Keep in mind that NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations. NumPy is built in C, so the types will be familiar to users of C.

# The Basics of NumPy Arrays

We will cover these categories of array manipulations:

* Attributes of arrays
* Indexing of arrays
* Slicing of arrays
* Reshaping of arrays
* Joining and splitting of arrays

In [14]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [15]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

('x3 ndim: ', 3)
('x3 shape:', (3, 4, 5))
('x3 size: ', 60)


In [16]:
print("dtype:", x3.dtype)

('dtype:', dtype('int64'))


In [17]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

('itemsize:', 8, 'bytes')
('nbytes:', 480, 'bytes')


**Array Indexing**

In [19]:
# Index from the end of the array
x1[-1]

9

**Array Slicing**

The thing to remember here is `s[start:stop:step]`

In [20]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[:5] # the first 5 elements

array([0, 1, 2, 3, 4])

In [22]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [23]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [24]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [25]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
print(x2[:, 0])  # first column of x2

[3 7 1]


In [28]:
print(x2[0, :])  # first row of x2

[3 5 2 4]


In [29]:
print(x2[0])  # equivalent to x2[0, :]

[3 5 2 4]


**Note**: array slices will return _views_, so they are not a copy of the data. To create a copy, follow below:

In [31]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[3 5]
 [7 6]]


**Reshaping Arrays**

In [32]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

**Array Concatenation and Splitting**

In [33]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [34]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [35]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [36]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

**Splitting of Arrays**

In [37]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))


In [38]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [40]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
