Here, we will learn how to compute summary statistics for the data in question. 

In [1]:
import numpy as np

In [2]:
L = np.random.random(100)
sum(L)

50.449946233409847

In [4]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 3: 85.1 ms per loop
1000 loops, best of 3: 589 µs per loop


In [5]:
min(big_array), max(big_array)

(3.9775249516260658e-07, 0.99999957823596386)

**Multi-dimensional aggregates**

We want to do aggregations along a row or column.

In [6]:
M = np.random.random((3, 4))
print(M)

[[ 0.35161372  0.63007298  0.16961356  0.50081927]
 [ 0.88472072  0.96433501  0.53323694  0.2395257 ]
 [ 0.24614418  0.14008406  0.01003941  0.83198444]]


In [7]:
M.sum()

5.5021899796933411

In [8]:
M.min(axis=0)

array([ 0.24614418,  0.14008406,  0.01003941,  0.2395257 ])

In [9]:
M.max(axis=1)

array([ 0.63007298,  0.96433501,  0.83198444])

head: data/president_heights.csv: No such file or directory
